[build]
target = "riscv64gc-unknown-none-elf"

[target.riscv64gc-unknown-none-elf]
rustflags = [
    "-Clink-arg=-Tsrc/linker.ld", 
    "-Cforce-frame-pointers=yes",
    # Compile with debug mode
    # "-Cdebug_assertions",
]