//! Manages the applications gathered in link_app.S, which is generated by
//! build.rs and executes the binaries in ../user/src/bin/
use crate::sync::UPSafeCell;
use crate::trap::TrapContext;
use core::arch::asm;
use core::arch::global_asm;
use lazy_static::*;

const MAX_APP_NUM: usize = 16;
const APP_BASE_ADDRESS: usize = 0x80400000;
const APP_SIZE_LIMIT: usize = 0x20000;
const USER_STACK_SIZE: usize = 4096 * 2;
const KERNEL_STACK_SIZE: usize = 4096 * 2;

#[repr(align(4096))]
struct KernelStack {
    data: [u8; KERNEL_STACK_SIZE],
}
impl KernelStack {
    pub fn get_sp(&self) -> usize {
        return self.data.as_ptr() as usize + KERNEL_STACK_SIZE;
    }
    pub fn push_context(&self, ctx: TrapContext) -> &'static mut TrapContext {
        let ctx_ptr = (self.get_sp() - core::mem::size_of::<TrapContext>()) as *mut TrapContext;
        unsafe {
            *ctx_ptr = ctx;
        }
        unsafe { ctx_ptr.as_mut().unwrap() }
    }
}
#[repr(align(4096))]
struct UserStack {
    data: [u8; USER_STACK_SIZE],
}
impl UserStack {
    pub fn get_sp(&self) -> usize {
        return self.data.as_ptr() as usize + USER_STACK_SIZE;
    }
}

static KERNEL_STACK: KernelStack = KernelStack {
    data: [0; KERNEL_STACK_SIZE],
};
static USER_STACK: UserStack = UserStack {
    data: [0; USER_STACK_SIZE],
};

struct AppManager {
    // The number of application.
    num_app: usize,
    // The index of running app.
    current_app: usize,
    // The start address each app.
    app_start: [usize; MAX_APP_NUM + 1],
}
global_asm!(include_str!("link_app.S"));
// The macro lazy_static would postpone the initialization until the first time
// variables are used.
lazy_static! {
    static ref APP_MANAGER: UPSafeCell<AppManager> = unsafe {
        UPSafeCell::new({
            extern "C" {
                fn _num_app();
            }
            let num_app_ptr = _num_app as usize as *const usize;
            let num_app = num_app_ptr.read_volatile();
            let mut app_start: [usize; MAX_APP_NUM + 1] = [0; MAX_APP_NUM + 1];
            let app_start_raw: &[usize] =
                core::slice::from_raw_parts(num_app_ptr.add(1), num_app + 1);
            app_start[..=num_app].copy_from_slice(app_start_raw);
            AppManager {
                num_app,
                current_app: 0,
                app_start,
            }
        })
    };
}

impl AppManager {
    pub unsafe fn load_app(&self, app_id: usize) {
        if app_id >= self.num_app {
            panic!("All applications completed!");
        }
        println!("[kernel] Loading app_{}", app_id);
        // Clear icache; Usually CPU might cache the instructions to increase
        // performance  and never expect text code changing; while in the
        // following we keep moving application code to BASE_ADDRESS before
        // we start running an application.
        asm!("fence.i");
        // Clear app area for the last applications.
        core::slice::from_raw_parts_mut(APP_BASE_ADDRESS as *mut u8, APP_SIZE_LIMIT).fill(0);
        // Move the application code to BASE_ADDRESS and ready to run.
        let app_src = core::slice::from_raw_parts(
            self.app_start[app_id] as *const u8,
            self.app_start[app_id + 1] - self.app_start[app_id],
        );
        let app_dst = core::slice::from_raw_parts_mut(APP_BASE_ADDRESS as *mut u8, app_src.len());
        app_dst.copy_from_slice(app_src);
        println!("[kernel] Load done app_{}", app_id);
    }
    pub fn get_current_app(&self) -> usize {
        self.current_app
    }
    pub fn move_to_next_app(&mut self) {
        self.current_app += 1;
    }
    pub fn print_app_info(&self) {
        println!("[kernel] num_app = {}", self.num_app);
        for i in 0..self.num_app {
            println!(
                "[kernel] app_{} [{:#x}, {:#x})",
                i,
                self.app_start[i],
                self.app_start[i + 1]
            );
        }
    }
}

pub fn init() {
    let app_manager = APP_MANAGER.exclusive_access();
    app_manager.print_app_info();
}

pub fn run_next_app() -> ! {
    let mut app_manager = APP_MANAGER.exclusive_access();
    let current_app = app_manager.get_current_app();
    unsafe {
        app_manager.load_app(current_app);
    }
    app_manager.move_to_next_app();
    drop(app_manager);
    println!("[kernel] restoring from kernel");
    extern "C" {
        fn __restore(ctx: usize);
    }
    unsafe {
        __restore(KERNEL_STACK.push_context(TrapContext::app_init_context(
            APP_BASE_ADDRESS,
            USER_STACK.get_sp(),
        )) as *const TrapContext as usize);
    }

    panic!("Unreachable in batch::run_current_app!");
}
